version: "2.4"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.10
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  api:
    build: .
    command: nodemon api.js
    ports:
      - 8082:8082
    volumes:
      - .:/usr/src/app
      - ./covers/:/usr/src/app/covers
      - ${AUDIOBOOK_DIR}:/usr/src/app/audiobooks
  aurelia:
    build:
      context: .
      dockerfile: Aurelia.Dockerfile
    command: au run --host 0.0.0.0 --port 8083
    ports:
      - 8083:8083
    volumes:
      - ./ui:/app
volumes:
  db_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./db_data"
